vim.api.nvim_set_keymap("n", "<F5>", "<Plug>VimspectorContinue", {})
vim.api.nvim_set_keymap("n", "<F3>", "<Plug>VimspectorStop", {})
vim.api.nvim_set_keymap("n", "<F4>", "<Plug>VimspectorRestart", {})
vim.api.nvim_set_keymap("n", "<F6>", "<Plug>VimspectorPause", {})
vim.api.nvim_set_keymap("n", "<F9>", "<Plug>VimspectorToggleBreakpoint", {})
vim.api.nvim_set_key("n", "<leader><F9>", "<Plug>VimspectorToggleConditionalBreakpoint", {})
vim.api.nvim_set_key("n", "<F8>", "<Plug>VimspectorAddFunctionBreakpoint", {})
vim.api.nvim_set_key("n", "<F10>", "<Plug>VimspectorStepOver", {})
vim.api.nvim_set_key("n", "<F11>", "<Plug>VimspectorStepInto", {})
vim.api.nvim_set_key("n", "<F12>", "<Plug>VimspectorStepOut", {})
vim.api.nvim_set_key("n", "<leader><F8>", "<Plug>VimspectorRunToCursor", {})

vim.cmd("autocmd BufNewFile,BufRead .vimspector.json setlocal filetype=jsonc")
