require("ibl").setup({
  indent = { char = "│" },
  scope = {
    enabled = true,
    show_start = false,
    show_end = false,
  },
  exclude = {
    filetypes = {
      "help",
      "dashboard",
      "dashpreview",
      "LuaTree",
      "vista",
      "sagahover",
      "coc-explorer",
      "lsputil_locations_list",
      "floaterm",
      "DiffviewFiles",
      "NvimTree",
      "vim",
      "packer",
      "lspinfo",
      "packer",
      "checkhealth",
      "help",
      "man",
      "gitcommit",
      "TelescopePrompt",
      "TelescopeResults",
      "''",
    },
  },
})
